version: '3'
services:
  mysql-standalone:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    ports:
      - "3307:3306"
  demo:
    image: demo
    restart: always
    ports:
      - "8082:8082"
   
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/demo?autoReconnect=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SERVER_ERROR_WHITELABEL_ENABLE: "false"
      SPRING_JPA_PROPERTIES.HIBERNATE.DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      
    build:
      context: "./"
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone